#!/bin/sh
NAME=$(echo "$0" | sed -e 's/.*\///' -e 's/-\?valgrind$//')
if [ -z "$NAME" ]; then
	echo "Not to be run directly"
	exit 1
fi
BINARY=""
for i in "./.libs/lt-$NAME" "./$NAME"; do
	if [ -x "$i" ]; then
		BINARY=$i
		break
	fi
done
if [ -n "$BINARY" ]; then
	LD_LIBRARY_PATH=../../src/.libs valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --log-fd=3 "$BINARY" "$@" 3> "$NAME.log"
else
	echo "$NAME not found"
fi
