#!/bin/sh
valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --log-fd=3 ./dcc7 "$@" 3> val7.log.tmp
pid=$(head -n 1 val7.log.tmp | cut -d' ' -f1)
grep "^$pid" val7.log.tmp > val7.log
rm -f val7.log.tmp
